"""add package_id to material_review, make generation_job_id nullable

Revision ID: 007bab636a92
Revises: db5774ac4667
Create Date: 2026-07-23 21:18:43.040558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007bab636a92'
down_revision = 'db5774ac4667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('generation_job_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_foreign_key(None, 'material_packages', ['package_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('generation_job_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('package_id')

    # ### end Alembic commands ###
