"""add link_job_id to notification

Revision ID: 02058b873a4b
Revises: 8c3b8c9f41d0
Create Date: 2026-07-22 14:59:56.693170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02058b873a4b'
down_revision = '8c3b8c9f41d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_job_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'generation_jobs', ['link_job_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('link_job_id')

    # ### end Alembic commands ###
