"""Add contact fields to Organization

Revision ID: 1793941aed0f
Revises: 5f0cadd3972b
Create Date: 2026-09-23 15:01:48.311153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1793941aed0f'
down_revision = '5f0cadd3972b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('website')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
