"""add task_id to generation_job for cancellation support

Revision ID: 446930fd34e6
Revises: 161f4e307a12
Create Date: 2026-07-22 10:07:18.404033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446930fd34e6'
down_revision = '161f4e307a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###
