"""add original_file_key to syllabus for viewing uploaded PDFs

Revision ID: 5f0cadd3972b
Revises: d70882702420
Create Date: 2026-08-16 21:17:01.567042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0cadd3972b'
down_revision = 'd70882702420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('syllabi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_file_key', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('syllabi', schema=None) as batch_op:
        batch_op.drop_column('original_file_key')

    # ### end Alembic commands ###
