"""add roles, reports_to, org trial fields

Revision ID: 7144e8946b98
Revises: 90637cde60a2
Create Date: 2026-07-21 21:31:29.330340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7144e8946b98'
down_revision = '90637cde60a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trial_ends_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reports_to_user_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['reports_to_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reports_to_user_id')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('trial_ends_at')

    # ### end Alembic commands ###
