"""add triggered_by_user_id to generation_job

Revision ID: 8c3b8c9f41d0
Revises: 446930fd34e6
Create Date: 2026-07-22 10:31:01.195861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c3b8c9f41d0'
down_revision = '446930fd34e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('triggered_by_user_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['triggered_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('triggered_by_user_id')

    # ### end Alembic commands ###
