"""add generation_job model

Revision ID: 90637cde60a2
Revises: a909cac13489
Create Date: 2026-07-21 10:44:19.453941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90637cde60a2'
down_revision = 'a909cac13489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('syllabus_id', sa.String(length=36), nullable=False),
    sa.Column('material_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('result_file_path', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['syllabus_id'], ['syllabi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generation_jobs')
    # ### end Alembic commands ###
