"""add MaterialPackage model, package_id and document_subtype on GenerationJob

Revision ID: db5774ac4667
Revises: 2f7a7bd45af6
Create Date: 2026-07-22 22:34:27.517919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db5774ac4667'
down_revision = '2f7a7bd45af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_packages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('syllabus_id', sa.String(length=36), nullable=False),
    sa.Column('triggered_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('package_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['syllabus_id'], ['syllabi.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('document_subtype', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'material_packages', ['package_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('document_subtype')
        batch_op.drop_column('package_id')

    op.drop_table('material_packages')
    # ### end Alembic commands ###
