"""Add eas_file_key to Syllabus for External Assessment Specification uploads

Revision ID: f39e17b6a0d4
Revises: 1793941aed0f
Create Date: 2026-09-23 22:46:26.966981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f39e17b6a0d4'
down_revision = '1793941aed0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('syllabi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eas_file_key', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('syllabi', schema=None) as batch_op:
        batch_op.drop_column('eas_file_key')

    # ### end Alembic commands ###
